// <auto-generated />
namespace Framework.MainEntity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updatefield1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatefield1));
        
        string IMigrationMetadata.Id
        {
            get { return "202209130627539_updatefield1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
